### A Pluto.jl notebook ###
# v1.0.1

using Markdown
using InteractiveUtils

# ╔═╡ 7cd03948-6b0f-11f1-315c-87a678136b72
begin
	using Pkg
	Pkg.activate(joinpath(@__DIR__, ".."))
end

# ╔═╡ 65ea2958-e50a-4942-a884-f76622160004
begin
	using RxInfer
	using ExponentialFamilyProjection
	using ClosedFormExpectations
	using SurrogateModelling
end

# ╔═╡ aa8a3f00-8551-485a-86a2-cde2973be07d
using Plots

# ╔═╡ 1c0ffee0-da7a-4b1d-9e55-5e7a0b1c2d3e
md"""
# Inferring a hidden rate from count data

**The setting.** We observe a long sequence of **counts** — one integer per time
step — generated by a *rate* that we believe drifts slowly and smoothly. The job
is to recover that hidden rate, with uncertainty, from the noisy counts: denoise
the data and reveal the underlying signal.

**The dataset.** `Sunspots()` loads the classic monthly **sunspot numbers** — how
many sunspots were counted on the Sun each month, recorded for more than two
centuries (over 3000 months). They rise and fall with the famous ~11-year solar
cycle on top of heavy month-to-month noise, and they are non-negative integers
$y_k$ — exactly the kind of data a Poisson model is built for.

**The model (a Poisson state-space model).** Each count is Poisson with a
time-varying rate, $y_k \sim \mathrm{Poisson}(\lambda_k)$. To keep the rate
positive and let it wander smoothly, we track its **log-rate**
$z_k = \log \lambda_k$ and let it follow a Gaussian random walk,
$z_k = z_{k-1} + \text{noise}$. So a slowly drifting latent $z_k$ produces the
bursty counts we observe; inference asks: given the counts, what was the log-rate
each month, and how sure are we?

**Why it isn't trivial — and what this notebook shows.** The random walk is
Gaussian and easy; the trouble is the Poisson observation, which is **not
conjugate** to the Gaussian state, so ordinary Gaussian message passing stalls at
each observation. We solve the *same model* **four** ways and compare them:

1. **CVI with mean-field (RxInfer, automatic).** Declare the model, add a
   mean-field + projection constraint, and let `infer` run conjugate-computation
   variational inference.
2. **NGMP (by hand).** Replace each Poisson leaf with a tailored Gaussian
   stand-in built from the closed-form **natural-gradient** message — the
   curvature averaged over the cavity, $\rho = e^{m+v/2}$ — then run exact
   Gaussian smoothing and iterate.
3. **NGMP delta-approximation (by hand).** The same loop, expanding at the mean
   but with the *pointwise* curvature $e^{m}$ — NGMP with the $e^{v/2}$ Fisher
   correction dropped.
4. **Laplace propagation (by hand).** The classical Laplace approximation as
   message passing: find the **mode** of each leaf's local belief
   (incoming message × Poisson energy) and expand the pointwise curvature
   $e^{\hat z}$ *there*.

The four agree on the trend but differ in the **uncertainty** they report, which
is the lesson of the comparison.
"""

# ╔═╡ 587a9f91-1091-4e11-8daa-6b1b8f49d435
sunspot_dataset = Sunspots()

# ╔═╡ c3b8e6a2-44d9-4f17-8aa5-1d9e7c0f2b41
# Monthly mean sunspot numbers as non-negative integer counts — the y_k that
# the Poisson leaf explains.
counts = round.(Int, sunspot_dataset.targets.average)

# ╔═╡ 9d2e1f70-5c83-4a0e-b6f4-8e72a1c5d930
md"""
## A Poisson state-space model with `PoissonExp`

An ordinary RxInfer model: a Gaussian random-walk on the latent **log-rate**
`z_k`, observed through the `PoissonExp` leaf from the package,

```math
z_1 \sim \mathcal N(m_0, v_0), \qquad
z_k \sim \mathcal N(z_{k-1}, \sigma^2), \qquad
y_k \sim \mathrm{PoissonExp}(z_k) \equiv \mathrm{Poisson}(e^{z_k}).
```
"""

# ╔═╡ 6f0a9b34-2d71-4e58-9c12-7b3f5a8e6d04
@model function poisson_state_space(y, σ, m0, v0)
	z[1] ~ Normal(mean = m0, variance = v0)
	y[1] ~ PoissonExp(z[1])
	for k in 2:length(y)
		z[k] ~ Normal(mean = z[k-1], variance = σ)
		y[k] ~ PoissonExp(z[k])
	end
end

# ╔═╡ a4d91587-22c6-4ee7-ae8d-2d20c95d3223
begin
	@constraints function mean_field_form_constraints()
		q(z) = MeanField()
		q(z) :: ProjectedTo(
						NormalMeanVariance, 
						parameters = ProjectionParameters(
							strategy = ClosedFormStrategy(),
						)
				)
	end
	
	@initialization function mean_field_init()
		q(z) = Normal(mean = 0, var = 100)
	end
	
	result = infer(
		model = poisson_state_space(σ = 0.1, m0 = 0.0, v0 = 10.0),
		constraints = mean_field_form_constraints(),
		data = ( y = counts,),
		initialization=mean_field_init(),
		options=(limit_stack_depth=100,),
		iterations = 10,
		free_energy=true
	)
end 

# ╔═╡ f5c554bc-7def-4580-8199-d6d71bd3a580
plot(
	 sunspot_dataset.features[!, :year], 
	 mean.(result.posteriors[:z][end])
)

# ╔═╡ ffdf6c8e-6cf8-497c-a4f5-d285b110be9e
plot(1:length(result.free_energy), result.free_energy,
     xlabel = "iteration", ylabel = "variational free energy", legend = false)

# ╔═╡ 3a9c1d52-7e84-4b16-9f23-1c8a5d0e2b47
md"""
**Method 1 — RxInfer, automatic (our converged reference).**
`result.free_energy` is the *variational free energy*, an upper bound on
$-\log p(y)$ that `infer` minimizes over its 10 iterations. Because it is a
**single objective**, it decreases monotonically and its flattening is the
signal that this method has converged. We will compare the by-hand surrogate
model below against this trusted, converged result.
"""

# ╔═╡ cb0918a8-8f86-45c1-aa1f-ddb26848a97e
md"""
## Opening the hood: the surrogate model

The cell above solved the model with RxInfer's **automatic** machinery: we
declared the `PoissonExp` leaves, added a mean-field + projection constraint,
and `infer` did everything. Below we rebuild the **same** inference *by hand*,
so you can see exactly what "project the Poisson leaf" means.

### Why plain Gaussian message passing fails

The latent chain $z_1 \to z_2 \to \dots$ is Gaussian, but every observation is a
Poisson count. The exact belief-propagation message a Poisson leaf sends back to
its edge $z_k$ is the log-likelihood

$$\ell_k(z_k) \;=\; \log \mathrm{Poisson}(y_k \mid e^{z_k}) \;=\; y_k\, z_k - e^{z_k} + \text{const}.$$

The $e^{z_k}$ makes this **not a parabola**, so it is not a Gaussian message and
Gaussian message passing cannot carry it unchanged.

### The surrogate leaf — the one idea to remember

Take the current Gaussian belief on the edge, $q_k = \mathcal N(m_k, v_k)$, and
**replace the Poisson leaf with the Gaussian message that best matches it there.**
Natural-gradient message passing tells us *which* Gaussian: the one whose
**natural parameters equal the gradient of $\mathbb E_{q_k}[\ell_k]$ in mean
coordinates**. With the only non-trivial moment $\rho_k = \mathbb E_{q_k}[e^{z_k}] = e^{m_k + v_k/2}$,

$$\underbrace{\xi_k = y_k + (m_k-1)\rho_k}_{\text{natural mean}}, \qquad \underbrace{\Lambda_k = \rho_k}_{\text{precision}},$$

i.e. a Gaussian message $\propto \exp\!\big(\xi_k z_k - \tfrac12 \Lambda_k z_k^2\big)$,
or equivalently a *fake observation* $\widetilde y_k = m_k + (y_k-\rho_k)/\rho_k$
with variance $R_k = 1/\Lambda_k$. We never type this formula by hand:
`poisson_surrogate` reads it straight from `ClosedWilliamsProduct` — the
closed-form Williams product of `PoissonExpression`, which returns exactly
$\nabla_{(m,\sigma)} \mathbb E_{q}[\ell]$.

### The outer loop (a fixed-point map)

Once every Poisson leaf is a Gaussian pseudo-observation, the graph is an
ordinary **normal–normal chain**, so a single `infer` on `lg_chain` runs exact
Gaussian smoothing (forward–backward). But the surrogate depends on the
marginal, which depends on the surrogate — so we iterate:

1. project every leaf at the current marginals $\to (\xi_k, \Lambda_k)$,
2. run **one** exact Gaussian BP sweep on the surrogate chain,
3. read the updated marginals, and repeat.

This is a fixed-point map $\lambda \leftarrow \Phi(\lambda)$; at a fixed point
the marginals stop changing.

### Damping and momentum

$\Phi$ need not be a contraction, so we take the step in natural-parameter space
with a damping factor `α` and **momentum** `β` (heavy-ball):

$$u \leftarrow \beta\,u + \alpha\big(\eta^\star - \eta\big), \qquad \eta \leftarrow \eta + u.$$

Momentum changes only the *path* to the solution, not the fixed point itself.

### This is **not** the same inference as the automatic run

The automatic run used `q(z) = MeanField()`, i.e. **mean-field variational
inference**: it forces the whole posterior to factorize, $q(z) = \prod_k q(z_k)$,
treating every state as independent. As is well known for mean-field, this
**does not estimate the variance correctly** — by assuming the states are
independent it throws away the temporal correlations, so the per-state
uncertainties it reports are off.

The surrogate model below keeps the chain **exact**: it replaces only the
Poisson leaves with Gaussian surrogates and then runs full forward–backward
Gaussian smoothing, so the joint covariance across time is preserved and the
posterior variances are the correct smoothed ones. This is the natural-gradient
message passing (NGMP) surrogate of §Surrogate Leaves; the paper contrasts it
with the mean-field route (VMP) in §VMP as the Classical Multi-Interface
Surrogate and §NGMP as the Improved Local Surrogate. The means come out close,
but the **uncertainty bands differ** — and that difference is the point.
"""

# ╔═╡ 2d3634c4-1b1b-42ab-bba9-0e0731f38af5
@model function lg_chain(y, R, σ, m0, v0)
    x[1] ~ Normal(mean = m0, variance = v0)
    y[1] ~ Normal(mean = x[1], variance = R[1])
    for k in 2:length(y)
        x[k] ~ Normal(mean = x[k-1], variance = σ)
        y[k] ~ Normal(mean = x[k],   variance = R[k])
    end
end

# ╔═╡ 0b00d09a-0422-4ac4-af57-1c4d7e278d8f
function poisson_surrogate(y::Real, m::Real, v::Real)
    ∂m, ∂σ = mean(
        ClosedWilliamsProduct(), 
        Logpdf(PoissonExpression(y)), 
        Normal(m, sqrt(v))
    )
    Λ = -∂σ / sqrt(v)
    ξ = ∂m + m * Λ
    return ξ, Λ
end

# ╔═╡ 11bded3d-294b-47c7-a29e-3a89b0c8bb76
function ngmp_poisson_smoother(y; σ = 0.1, m0 = 0.0, v0 = 10.0,
                               iters = 10, α = 0.5, β = 0.2)
    N = length(y)
    m = log.(y .+ 1.0); v = fill(1.0, N)          # initial edge marginals
    ξ = zeros(N); Λ = zeros(N)                     # surrogate message state η
    vξ = zeros(N); vΛ = zeros(N)                   # momentum buffers
    surrogate_free_energy = Float64[]              # Bethe FE of each frozen surrogate
    update_norm = Float64[]                        # fixed-point residual ‖Φ(λ)-λ‖∞
    local inference                                 # last inner BP result, kept below
    for _ in 1:iters
        s = poisson_surrogate.(y, m, v)            # project every leaf at q_k
        ηξ = first.(s); ηΛ = last.(s)
        @. vξ = β * vξ + α * (ηξ - ξ); @. ξ += vξ
        @. vΛ = β * vΛ + α * (ηΛ - Λ); @. Λ += vΛ
        inference = infer(
                     model = lg_chain(σ = σ, m0 = m0, v0 = v0),
                     data = (y = ξ ./ Λ, R = 1.0 ./ Λ),
                     options = (limit_stack_depth = 100,),
                     free_energy = true,
        )
        post = inference.posteriors[:x]
        mnew = mean.(post); vnew = var.(post)
        push!(surrogate_free_energy, inference.free_energy[end])
        push!(update_norm, max(maximum(abs.(mnew .- m)), maximum(abs.(vnew .- v))))
        m, v = mnew, vnew
    end
    return (inference = inference, means = m, variances = v,
            surrogate_free_energy = surrogate_free_energy, update_norm = update_norm)
end

# ╔═╡ af2b5341-66fe-4ff5-ad4b-bb7c4ab9b309
ngmp_result = ngmp_poisson_smoother(counts)

# ╔═╡ d1e2f3a4-0001-4b1c-9d2e-5f6a7b8c9d01
md"""
## Two more surrogates: the NGMP delta approximation and Laplace propagation

NGMP builds each leaf's Gaussian message from the **variance-aware** curvature
$-\mathbb E_q[\ell''] = e^{m+v/2}$ — the expected (Fisher) information, *averaged*
over the marginal $q=\mathcal N(m,v)$. Two classical surrogates are obtained by
peeling that apart along **two independent axes**: (i) *expected* vs *pointwise*
(observed) curvature, and (ii) expand at the **marginal mean** $m$ vs at the
**belief mode** $\hat z$.

| method | expand at | curvature | $\rho$ |
|:--|:--|:--|:--|
| **NGMP** | marginal mean $m$ | expected (Fisher) $-\mathbb E_q[\ell'']$ | $e^{m+v/2}$ |
| **NGMP delta-approx** | marginal mean $m$ | observed $-\ell''(m)$ | $e^{m}$ |
| **Laplace propagation** | belief **mode** $\hat z$ | observed $-\ell''(\hat z)$ | $e^{\hat z}$ |

**NGMP delta-approx.** Apply the quadratic delta approximation to $\ell$ about the
marginal *mean*: $\mathbb E_q[\ell'']\to\ell''(m)$, dropping the $e^{v/2}$ Fisher
factor. Same expansion point as NGMP, just the pointwise curvature. We read it off
the **same** `ClosedWilliamsProduct` evaluated at the deterministic point $z=m$
(zero variance), so the score collapses to $\partial_m=\ell'(m)=y-e^{m}$ and
$\Lambda=-\ell''(m)=y-\partial_m=e^{m}$.

**Laplace propagation** (Smola–Vishwanathan–Eskin, 2003) is the message-passing
form of the classical Laplace approximation: pin a Gaussian at the **mode of the
local belief** and read its width off the **pointwise Hessian** there. At edge
$z_k$ the recipe is literally:

1. Take the **incoming message** $\mu_{-}(z)=\mathcal N(z; m_-, 1/P_-)$ — the
   cavity, everything the chain sends *into* $z_k$ *except* the Poisson leaf.
2. Add the exact Poisson energy and find the **mode of the product**,
   ```math
   \hat z = \arg\max_z \Big[ -\tfrac{P_-}{2}(z-m_-)^2 \;+\; \underbrace{y\,z - e^{z}}_{\ell(z)} \Big],
   \qquad\text{i.e. solve}\quad P_-(m_- - z) + y - e^{z} = 0 .
   ```
3. Expand the leaf at that mode: precision $\Lambda=-\ell''(\hat z)=e^{\hat z}$,
   natural mean $\xi=\ell'(\hat z)+\hat z\,\Lambda$. Read off the **same**
   `ClosedWilliamsProduct` at the deterministic point $z=\hat z$.

The delta-approx is a *Laplace–Fisher hybrid* — observed curvature but expanded at
the **mean**, not the mode. It coincides with true Laplace only at a fixed point
where $m=\hat z$; the mode solve makes Laplace expand where the belief actually
peaks at every sweep.
"""

# ╔═╡ d1e2f3a4-0002-4b1c-9d2e-5f6a7b8c9d02
function ngmp_delta_surrogate(y::Real, m::Real, ::Real)  # third arg (variance) unused: delta uses the mean only
    # NGMP delta approximation: quadratic-delta of ℓ about the marginal MEAN m,
    # which drops the eᵛ/² Fisher factor (E_q[ℓ''] → ℓ''(m)). Same expansion point
    # as NGMP, observed curvature instead of expected. Evaluate the SAME Williams
    # product at the deterministic point z = m (zero variance): ∂m = ℓ'(m) = y−eᵐ.
    # (∂σ = −σ·eᵐ → 0 here, so NGMP's Λ = −∂σ/√v is 0/0 — recover Λ from the score.)
    ∂m, _ = mean(
        ClosedWilliamsProduct(),
        Logpdf(PoissonExpression(y)),
        Normal(m, 0.0),
    )
    Λ = y - ∂m            # −ℓ''(m) = eᵐ   (NGMP's ρ = eᵐ⁺ᵛ/² with the v/2 dropped)
    ξ = ∂m + m * Λ        # natural-mean parameter, exactly as in `poisson_surrogate`
    return ξ, Λ
end

# ╔═╡ d1e2f3a4-0003-4b1c-9d2e-5f6a7b8c9d03
function ngmp_delta_smoother(y; σ = 0.1, m0 = 0.0, v0 = 10.0,
                             iters = 10, α = 0.5, β = 0.2)
    N = length(y)
    m = log.(y .+ 1.0); v = fill(1.0, N)          # initial edge marginals
    ξ = zeros(N); Λ = zeros(N)                     # surrogate message state η
    vξ = zeros(N); vΛ = zeros(N)                   # momentum buffers
    surrogate_free_energy = Float64[]              # Bethe FE of each frozen surrogate
    update_norm = Float64[]                        # fixed-point residual ‖Φ(λ)-λ‖∞
    local inference                                 # last inner BP result, kept below
    for _ in 1:iters
        s = ngmp_delta_surrogate.(y, m, v)         # expand every leaf at the mean
        ηξ = first.(s); ηΛ = last.(s)
        @. vξ = β * vξ + α * (ηξ - ξ); @. ξ += vξ
        @. vΛ = β * vΛ + α * (ηΛ - Λ); @. Λ += vΛ
        inference = infer(
                     model = lg_chain(σ = σ, m0 = m0, v0 = v0),
                     data = (y = ξ ./ Λ, R = 1.0 ./ Λ),
                     options = (limit_stack_depth = 100,),
                     free_energy = true,
        )
        post = inference.posteriors[:x]
        mnew = mean.(post); vnew = var.(post)
        push!(surrogate_free_energy, inference.free_energy[end])
        push!(update_norm, max(maximum(abs.(mnew .- m)), maximum(abs.(vnew .- v))))
        m, v = mnew, vnew
    end
    return (inference = inference, means = m, variances = v,
            surrogate_free_energy = surrogate_free_energy, update_norm = update_norm)
end

# ╔═╡ d1e2f3a4-0004-4b1c-9d2e-5f6a7b8c9d04
ngmp_delta_result = ngmp_delta_smoother(counts)

# ╔═╡ d1e2f3a4-0006-4b1c-9d2e-5f6a7b8c9d06
md"""
### True Laplace propagation — mode of (incoming message × Poisson energy)

`poisson_belief_mode` Newton-solves $P_-(m_- - z) + y - e^{z} = 0$ for the mode
$\hat z$ of the local belief (Gaussian cavity × Poisson energy). The belief is
strictly log-concave ($\ell'' = -e^{z} < 0$), so Newton converges quadratically
from the cavity mean. `laplace_surrogate` then expands the leaf at $\hat z$ and the
`laplace_smoother` reconstructs the cavity $(m_-, P_-)$ each sweep as
*marginal ÷ current leaf* before relinearising.
"""

# ╔═╡ d1e2f3a4-0007-4b1c-9d2e-5f6a7b8c9d07
function poisson_belief_mode(y::Real, m₋::Real, P₋::Real; newton_iters = 8)
    # mode of  −½ P₋ (z − m₋)² + (y·z − eᶻ):  solve  P₋(m₋ − z) + y − eᶻ = 0
    z = m₋                                   # warm start at the cavity mean
    for _ in 1:newton_iters
        ez = exp(z)
        g  = P₋ * (m₋ - z) + y - ez          # ∂z log-belief
        h  = -P₋ - ez                        # ∂²z log-belief  (< 0, concave)
        z -= g / h
    end
    return z
end

# ╔═╡ d1e2f3a4-0008-4b1c-9d2e-5f6a7b8c9d08
function laplace_surrogate(y::Real, m₋::Real, P₋::Real)
    # Laplace propagation: expand ℓ at the mode ẑ of the belief (cavity × leaf),
    # NOT at the marginal mean. Read the surrogate off the SAME Williams product at
    # the deterministic point z = ẑ: ∂m = ℓ'(ẑ) = y − eᶻ̂, Λ = −ℓ''(ẑ) = y − ∂m = eᶻ̂.
    ẑ = poisson_belief_mode(y, m₋, P₋)
    ∂m, _ = mean(
        ClosedWilliamsProduct(),
        Logpdf(PoissonExpression(y)),
        Normal(ẑ, 0.0),
    )
    Λ = y - ∂m            # −ℓ''(ẑ) = eᶻ̂  (observed information at the belief mode)
    ξ = ∂m + ẑ * Λ        # natural-mean parameter, expanded at the mode
    return ξ, Λ
end

# ╔═╡ d1e2f3a4-0009-4b1c-9d2e-5f6a7b8c9d09
function laplace_smoother(y; σ = 0.1, m0 = 0.0, v0 = 10.0,
                          iters = 10, α = 0.5, β = 0.2)
    N = length(y)
    m = log.(y .+ 1.0); v = fill(1.0, N)          # initial edge marginals
    ξ = zeros(N); Λ = zeros(N)                     # surrogate message state η
    vξ = zeros(N); vΛ = zeros(N)                   # momentum buffers
    surrogate_free_energy = Float64[]              # Bethe FE of each frozen surrogate
    update_norm = Float64[]                        # fixed-point residual ‖Φ(λ)-λ‖∞
    local inference                                 # last inner BP result, kept below
    for _ in 1:iters
        # incoming (cavity) message on each edge = current marginal ÷ current leaf
        P₋ = max.(1.0 ./ v .- Λ, 1e-8)             # cavity precision (guard > 0)
        m₋ = (m ./ v .- ξ) ./ P₋                   # cavity mean
        s = laplace_surrogate.(y, m₋, P₋)          # expand each leaf at the belief mode
        ηξ = first.(s); ηΛ = last.(s)
        @. vξ = β * vξ + α * (ηξ - ξ); @. ξ += vξ
        @. vΛ = β * vΛ + α * (ηΛ - Λ); @. Λ += vΛ
        inference = infer(
                     model = lg_chain(σ = σ, m0 = m0, v0 = v0),
                     data = (y = ξ ./ Λ, R = 1.0 ./ Λ),
                     options = (limit_stack_depth = 100,),
                     free_energy = true,
        )
        post = inference.posteriors[:x]
        mnew = mean.(post); vnew = var.(post)
        push!(surrogate_free_energy, inference.free_energy[end])
        push!(update_norm, max(maximum(abs.(mnew .- m)), maximum(abs.(vnew .- v))))
        m, v = mnew, vnew
    end
    return (inference = inference, means = m, variances = v,
            surrogate_free_energy = surrogate_free_energy, update_norm = update_norm)
end

# ╔═╡ d1e2f3a4-0005-4b1c-9d2e-5f6a7b8c9d05
laplace_result = laplace_smoother(counts)

# ╔═╡ b7150c92-698e-4410-9fff-62b5652071ff
begin
	years = sunspot_dataset.features[!, :year]
	rxi   = result.posteriors[:z][end]

	# 95% credible bands (±1.96σ) for all four posteriors.
	plot(years, ngmp_result.means;
	     ribbon = 1.96 .* sqrt.(ngmp_result.variances), fillalpha = 0.15,
	     lw = 2, color = :dodgerblue, label = "NGMP (expected info, mean)",
	     xlabel = "year", ylabel = "log-rate  z_k",
	     title = "Posterior log-rate ± 95% credible band")
	plot!(years, ngmp_delta_result.means;
	      ribbon = 1.96 .* sqrt.(ngmp_delta_result.variances), fillalpha = 0.15,
	      lw = 2, color = :purple, label = "NGMP delta-approx (observed info, mean)")
	plot!(years, laplace_result.means;
	      ribbon = 1.96 .* sqrt.(laplace_result.variances), fillalpha = 0.15,
	      lw = 2, color = :seagreen, label = "Laplace propagation (observed info, mode)")
	plot!(years, mean.(rxi);
	      ribbon = 1.96 .* sqrt.(var.(rxi)), fillalpha = 0.15,
	      lw = 2, color = :darkorange, label = "CVI + mean-field")
end

# ╔═╡ 6f2e8b91-4d05-42c7-a8e1-9b3c7f1a6d50
md"""
**Reading the comparison.** Four methods on the *same* model: **blue** NGMP
(expected/Fisher info at the mean, $\rho = e^{m+v/2}$), **purple** the NGMP
delta-approx (observed info at the mean, $\rho_0 = e^{m}$), **green** true Laplace
propagation (observed info at the belief *mode*, $\rho_0 = e^{\hat z}$), and
**orange** the automatic CVI + mean-field run. All four posterior **means** track
each other closely and follow the ~11-year solar cycle. The shaded bands are 95%
credible intervals ($\pm 1.96\sigma$), and that is where they part ways:

- **CVI + mean-field** factorises $q(z)=\prod_k q(z_k)$, throwing away the temporal
  correlations, so it does **not** report the right variance.
- The three surrogate methods all keep the chain **exact** and report the correct
  *smoothed* uncertainty. They differ only in how each leaf's pseudo-precision is
  built:
    - **NGMP vs delta-approx** isolate the **Fisher correction**: same expansion
      point (the mean), $\rho = e^{m+v/2}$ vs $\rho_0 = e^{m}$. NGMP's curvature is
      always the larger, so its bands are marginally **tighter** wherever $v$ is
      large.
    - **delta-approx vs Laplace** isolate the **expansion point**: same observed
      curvature, but evaluated at the mean $m$ vs the belief mode $\hat z$. They
      agree exactly at a fixed point (where $m=\hat z$) and differ only on the
      transient / where the belief is skewed.

The gaps are largest in the deep solar minima (long runs of near-zero counts),
where the data constrain $z_k$ least, $v$ is largest, and the skew between mean
and mode is most pronounced.
"""

# ╔═╡ 8c4d2a16-9b73-41e8-b5f2-0a6e3d9c1f84
md"""
### Free energy of the surrogate loops — they converge

We benchmark against a **converged** reference (Method 1's variational free
energy flattened), so we want the surrogate loops (NGMP shown here; the
delta-approx and Laplace loops behave the same way) to converge too — but read the
free energy carefully. The curve below is the Bethe free energy of the surrogate
built at each sweep, and **every sweep freezes a different Gaussian surrogate**.
So, unlike Method 1, it is **not a single objective** and need not decrease
monotonically.

What you see is the typical surrogate behaviour: a **spike early on** — the
surrogate starts with *no* Poisson evidence ($\eta = 0$) and overshoots while it
ramps up — and then it **settles** to a stable value. That settling *is* the
convergence: by the last sweeps the frozen surrogate, and hence its free energy,
stops moving. For a check that does not rely on monotonicity,
`ngmp_result.update_norm` records $\lVert\Phi(\lambda)-\lambda\rVert_\infty$ —
the largest change in any marginal per sweep — which falls straight to ≈0.
"""

# ╔═╡ e2a7b3c1-5d64-4f08-9b12-7c3e8a1f6d29
# Surrogate Bethe free energy. NOTE: each outer iteration freezes a *different*
# Gaussian surrogate, so this is a diagnostic, not a single objective being
# minimized — it need not decrease monotonically (see §Damping and Momentum).
# However it converges anyway :ballon:
plot(1:length(ngmp_result.surrogate_free_energy), ngmp_result.surrogate_free_energy,
     xlabel = "outer iteration", ylabel = "surrogate Bethe free energy",
     legend = false)

# ╔═╡ Cell order:
# ╟─1c0ffee0-da7a-4b1d-9e55-5e7a0b1c2d3e
# ╠═7cd03948-6b0f-11f1-315c-87a678136b72
# ╠═65ea2958-e50a-4942-a884-f76622160004
# ╠═587a9f91-1091-4e11-8daa-6b1b8f49d435
# ╠═c3b8e6a2-44d9-4f17-8aa5-1d9e7c0f2b41
# ╟─9d2e1f70-5c83-4a0e-b6f4-8e72a1c5d930
# ╠═6f0a9b34-2d71-4e58-9c12-7b3f5a8e6d04
# ╠═a4d91587-22c6-4ee7-ae8d-2d20c95d3223
# ╠═aa8a3f00-8551-485a-86a2-cde2973be07d
# ╠═f5c554bc-7def-4580-8199-d6d71bd3a580
# ╠═ffdf6c8e-6cf8-497c-a4f5-d285b110be9e
# ╟─3a9c1d52-7e84-4b16-9f23-1c8a5d0e2b47
# ╟─cb0918a8-8f86-45c1-aa1f-ddb26848a97e
# ╠═2d3634c4-1b1b-42ab-bba9-0e0731f38af5
# ╠═0b00d09a-0422-4ac4-af57-1c4d7e278d8f
# ╠═11bded3d-294b-47c7-a29e-3a89b0c8bb76
# ╠═af2b5341-66fe-4ff5-ad4b-bb7c4ab9b309
# ╟─d1e2f3a4-0001-4b1c-9d2e-5f6a7b8c9d01
# ╠═d1e2f3a4-0002-4b1c-9d2e-5f6a7b8c9d02
# ╠═d1e2f3a4-0003-4b1c-9d2e-5f6a7b8c9d03
# ╠═d1e2f3a4-0004-4b1c-9d2e-5f6a7b8c9d04
# ╟─d1e2f3a4-0006-4b1c-9d2e-5f6a7b8c9d06
# ╠═d1e2f3a4-0007-4b1c-9d2e-5f6a7b8c9d07
# ╠═d1e2f3a4-0008-4b1c-9d2e-5f6a7b8c9d08
# ╠═d1e2f3a4-0009-4b1c-9d2e-5f6a7b8c9d09
# ╠═d1e2f3a4-0005-4b1c-9d2e-5f6a7b8c9d05
# ╠═b7150c92-698e-4410-9fff-62b5652071ff
# ╟─6f2e8b91-4d05-42c7-a8e1-9b3c7f1a6d50
# ╟─8c4d2a16-9b73-41e8-b5f2-0a6e3d9c1f84
# ╠═e2a7b3c1-5d64-4f08-9b12-7c3e8a1f6d29
